Github workflow build feature branch version validation

diff --git a/.github/workflows/create-feature-branch.yaml b/.github/workflows/create-feature-branch.yaml
--- a/.github/workflows/create-feature-branch.yaml
+++ b/.github/workflows/create-feature-branch.yaml
@@ -1,7 +1,9 @@
+#Create a new feature branch from the develop branch.
+
 name: Create feature branch
 
 on:
-  #Enable manual trigger.
+  #Enable the workflow to be manually triggered. The workflow must be pushed to the default branch at least once.
   workflow_dispatch:
     inputs:
       branch_name:
@@ -24,28 +26,70 @@ jobs:
     runs-on: self-hosted
 
     steps:
-      - name: Validate branch name
+        #Check the name format of the new branch name input.
+      - name: Validate input branch name
         run: |
-          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
+          INPUT_BRANCH_NAME="${{ github.event.inputs.branch_name }}"
 
           #Save input to a global variable. 
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV 
-          echo "Input branch name: ${BRANCH_NAME}" 
+          echo "INPUT_BRANCH_NAME=$INPUT_BRANCH_NAME" >> $GITHUB_ENV 
+          echo "Input branch name: ${INPUT_BRANCH_NAME}" 
 
           #Allowed patterns.
           #PATTERN="^(feature|bugfix)\/[a-z]+-[0-9]+-[a-z0-9-]+$|^release\/[0-9]+\.[0-9]+\.[0-9]+$"
-          PATTERN="^(feature)\/[a-z]+-[0-9]+-[a-z0-9-]+$"
+          PATTERN="/([a-z0-9]+)/"
 
-          if [[ ! ${BRANCH_NAME} =~ $PATTERN ]]; then
-            echo "❌ Invalid branch name: ${BRANCH_NAME}"
-            echo "Allowed formats: feature/description"
+          if [[ ! ${INPUT_BRANCH_NAME} =~ $PATTERN ]]; then
+            echo "❌ Invalid branch name: ${INPUT_BRANCH_NAME}"
+            echo "Allowed formats: Lower case, upper case and numbers"
             exit 1
+          else
+            echo "✅ Branch name is valid"
           fi
 
-          echo "✅ Branch name is valid"
+        #Checkout the parent branch specifically since we are creating the new one from it.
+      - name: Checkout code
+        uses: actions/checkout@v4
+        ref: develop
+
+        #Check if the version number is in the correct format.
+      - name: Validate version number
+        run: |
+          echo "Version file: ${VERSION_FILE}"
+
+          #Read the version file.
+          VERSION_NUMBER=$(jq -r '.version' ${VERSION_FILE} | tr -d '\n')
+
+          #If node is installed in the runtime environment.
+          #VERSION_NUMBER=$(node -p "require('./package.json').version") 
+          
+          #Append the version number variable to the array of runtime variables.
+          echo "VERSION_NUMBER=VERSION_NUMBER" >> $GITHUB_ENV
+          echo "Version number: ${VERSION_NUMBER}"
+          
+          #Allowed patterns.
+          PATTERN="/([0-9]+\.[0-9]+\.[0]){1,1}/"
+
+          if [[ ! ${VERSION_NUMBER} =~ $PATTERN ]]; then
+            echo "❌ Version number ${VERSION_NUMBER} is inconsistent with the format. Exiting!"
+            echo "Allowed formats: x.x.0"
+            exit 1
+          else
+            echo "Version number ${VERSION_NUMBER} is consistent with the format"
+          fi
+
+        #Prepare the new branch name with the necessary appends.
+      - name: Prepare feature branch name
+        id: meta
+        run: | 
+          #Append the necessary components.
+          NEW_BRANCH_NAME="feature\/${VERSION_NUMBER}\/${INPUT_BRANCH_NAME}"
+          echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_ENV
+          echo "New branch name: ${NEW_BRANCH_NAME}"
        
+        #Create the new branch and oush it to remote.
       - name: Create and push branch
         run: |
-          git checkout ${PARENT_BRANCH}
-          git checkout -b ${BRANCH_NAME}
-          git push origin ${BRANCH_NAME}
+          #git checkout ${PARENT_BRANCH}
+          git checkout -b ${NEW_BRANCH_NAME}
+          git push origin ${NEW_BRANCH_NAME}
